// citrine/testbed/golden-admin/app/src/components/TrendChart.vue
<script setup>
// 趋势折线（工作台「订单趋势」）：直接用桥接的 trendLine 配方——y 轴贴数据范围、平滑 0.3、不显示数据点、多序列不填面积。
import EChart from './EChart.vue'
import { trendLine, areaGradient } from '../styles/bridge/echarts.js'

const props = defineProps({ days: Array, series: Array })
const option = (t, echarts) => trendLine({ days: props.days, series: props.series, area: props.series.length === 1 ? areaGradient(echarts) : undefined })
</script>

<template><EChart :option="option" /></template>

// citrine/seeds/brand-yellow-e/bridge/react/TrendChart.tsx
// 趋势折线（种子配方组件 · React 版）：桥接 trendLine 配方——计数型自动整数刻度、单序列渐变面积、多序列不填面积。
import * as React from 'react'
import { EChart } from './EChart'
import { trendLine, areaGradient } from '../echarts.js'

export function TrendChart({ days, series, count }: { days: string[]; series: { name: string; data: number[] }[]; count?: boolean }) {
  return <EChart deps={[days, series, count]} option={(t, ec) => trendLine({ days, series, count, area: series.length === 1 ? areaGradient(ec) : undefined })} />
}
