// morganite/testbed/shadcn-lab/app/src/App.tsx
// Morganite × shadcn/ui 实验室：验证 bridge/shadcn.css 在真实 React + Tailwind v4 + Radix 组件上的渲染结果，
// 同时验证与组件库无关的配方层（recipes.css）和 React 版配方组件（bridge/react）能否直接复用。
// 壳层用 recipes.css 的 .app / .sidebar / .nav / .topbar / .content；没有路由库，hash 路由手写。
import * as React from 'react'
import { LayoutDashboard, ListOrdered, FilePenLine, Boxes, Menu, Moon, Sun, Bell, Search } from 'lucide-react'
import { Kitchen } from './pages/Kitchen'
import { Orders } from './pages/Orders'
import { Dashboard } from './pages/Dashboard'
import { FormPage } from './pages/FormPage'

const ROUTES: Record<string, { title: string; group: string; icon: React.ComponentType<{ className?: string }>; page: React.ComponentType }> = {
  '/': { title: '工作台', group: '概览', icon: LayoutDashboard, page: Dashboard },
  '/orders': { title: '单据管理', group: '业务', icon: ListOrdered, page: Orders },
  '/form': { title: '新建供应商', group: '业务', icon: FilePenLine, page: FormPage },
  '/kitchen': { title: '组件走查', group: '系统', icon: Boxes, page: Kitchen }
}

function useHash() {
  const [hash, setHash] = React.useState(() => location.hash.replace(/^#/, '') || '/')
  React.useEffect(() => { const on = () => setHash(location.hash.replace(/^#/, '').split('?')[0] || '/'); window.addEventListener('hashchange', on); return () => window.removeEventListener('hashchange', on) }, [])
  return hash.split('?')[0]
}

export default function App() {
  const path = useHash()
  const route = ROUTES[path] ?? ROUTES['/']
  const [collapsed] = React.useState(() => matchMedia('(max-width: 992px)').matches)   // layout.breakpoint.narrow 字面镜像
  const [navOpen, setNavOpen] = React.useState(false)   // 手机抽屉（≤ 768，layout.breakpoint.mobile 字面镜像）
  React.useEffect(() => { setNavOpen(false) }, [path])
  React.useEffect(() => { const mq = matchMedia('(max-width: 768px)'); const on = () => setNavOpen(false); mq.addEventListener('change', on); return () => mq.removeEventListener('change', on) }, [])
  const [dark, setDark] = React.useState(() => document.documentElement.classList.contains('dark'))
  const toggleTheme = () => { const next = !dark; setDark(next); document.documentElement.classList.toggle('dark', next); localStorage.setItem('sl-theme', next ? 'dark' : 'light') }
  React.useEffect(() => { document.title = `${route.title} · Morganite × shadcn 实验室` }, [route])
  const groups = [...new Set(Object.values(ROUTES).map((r) => r.group))]
  const Page = route.page
  return (
    <div className={`app${collapsed ? ' is-collapsed' : ''}${navOpen ? ' is-nav-open' : ''}`}>
      <aside className="sidebar">
        <div className="app-brand"><span className="logo">M</span>{!collapsed && <span>shadcn 实验室</span>}</div>
        <nav className="nav" aria-label="主导航">
          {groups.map((g) => (
            <React.Fragment key={g}>
              <div className="nav-group">{g}</div>
              {Object.entries(ROUTES).filter(([, r]) => r.group === g).map(([p, r]) => (
                <a key={p} href={`#${p}`} className={p === path ? 'active' : undefined} aria-label={r.title} aria-current={p === path ? 'page' : undefined}>
                  <r.icon className="i-icon--lg" /><span className="nav-label">{r.title}</span>
                </a>
              ))}
            </React.Fragment>
          ))}
        </nav>
        <div className="sidebar-foot">{collapsed ? '0.1' : 'Morganite 0.1 · shadcn'}</div>
      </aside>
      {navOpen && <button className="sidebar-mask" aria-label="关闭菜单" onClick={() => setNavOpen(false)} />}
      <div className="main">
        <header className="topbar">
          <button className="iconbtn menu-btn" title="打开菜单" onClick={() => setNavOpen(true)}><Menu className="i-icon--lg" /></button>
          <nav aria-label="面包屑" className="crumbs"><span>{route.group}</span><span className="sep" aria-hidden="true">/</span><span>{route.title}</span></nav>
          <label className="search"><Search className="i-icon--sm" aria-hidden="true" /><input type="search" placeholder="搜索订单、商户、报表…" aria-label="搜索" /></label>
          <button className="iconbtn" title="通知（3 条未读）" aria-label="通知，3 条未读"><Bell className="i-icon--lg" /><span className="unread num">3</span></button>
          <button className={`iconbtn${dark ? ' is-on' : ''}`} title={dark ? '切换亮色' : '切换暗色'} onClick={toggleTheme}>{dark ? <Sun className="i-icon--lg" /> : <Moon className="i-icon--lg" />}</button>
          <span className="user" role="button" tabIndex={0} aria-haspopup="menu"><span className="avatar" aria-hidden="true">王</span><span className="user-name">王小明 · 管理员</span></span>
        </header>
        <main className="content"><Page /></main>
      </div>
    </div>
  )
}

// morganite/testbed/element-lab/app/src/App.vue
<script setup>
import { computed, onBeforeUnmount, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { Home, ApplicationTwo, Search, MenuFold, MenuUnfold, HamburgerButton } from '@icon-park/vue-next'

const route = useRoute()
const router = useRouter()
// 三端（layout.breakpoint.narrow / mobile 的字面镜像 992 / 768）：窄屏侧栏默认折叠；手机侧栏是离屏抽屉，汉堡开、遮罩 / 换页关
const mqNarrow = matchMedia('(max-width: 992px)')
const mqMobile = matchMedia('(max-width: 768px)')
const collapsed = ref(mqNarrow.matches)
const isMobile = ref(mqMobile.matches)
const navOpen = ref(false)
const onNarrow = (e) => { collapsed.value = e.matches }
const onMobile = (e) => { isMobile.value = e.matches; navOpen.value = false }
mqNarrow.addEventListener('change', onNarrow)
mqMobile.addEventListener('change', onMobile)
onBeforeUnmount(() => { mqNarrow.removeEventListener('change', onNarrow); mqMobile.removeEventListener('change', onMobile) })
router.afterEach(() => { navOpen.value = false })

const nav = [
  { group: '概览', items: [{ to: '/', label: '工作台', icon: Home }] },
  { group: '实测', items: [{ to: '/kitchen', label: '组件走查', icon: ApplicationTwo }] }
]
const title = computed(() => route.meta.title)
</script>

<template>
  <div class="app" :class="{ 'is-collapsed': collapsed, 'is-nav-open': navOpen }">
    <aside class="sidebar">
      <div class="app-brand"><span class="logo">M</span><span>玫瑰金后台</span></div>
      <nav class="nav" aria-label="主导航">
        <template v-for="g in nav" :key="g.group">
          <div class="nav-group">{{ g.group }}</div>
          <router-link v-for="i in g.items" :key="i.to" :to="i.to" :class="{ active: route.path === i.to }" :aria-label="i.label">
            <component :is="i.icon" class="i-icon--md" /><span class="nav-label">{{ i.label }}</span>
          </router-link>
        </template>
      </nav>
      <div class="sidebar-foot">{{ collapsed && !isMobile ? '0.1' : 'Morganite 0.1 · 实测' }}</div>
    </aside>

    <button v-if="navOpen" class="sidebar-mask" aria-label="关闭菜单" @click="navOpen = false" />

    <div class="main">
      <header class="topbar">
        <button class="iconbtn menu-btn" type="button" aria-label="打开菜单" @click="navOpen = true"><HamburgerButton class="i-icon--lg" /></button>
        <button class="iconbtn collapse-btn" type="button" :aria-label="collapsed ? '展开菜单' : '折叠菜单'" @click="collapsed = !collapsed">
          <component :is="collapsed ? MenuUnfold : MenuFold" class="i-icon--lg" />
        </button>
        <el-breadcrumb separator="/"><el-breadcrumb-item>实测</el-breadcrumb-item><el-breadcrumb-item>{{ title }}</el-breadcrumb-item></el-breadcrumb>
        <el-input class="search" placeholder="搜索资产、交易、报表…" :prefix-icon="Search" aria-label="全局搜索" />
      </header>
      <main class="content"><router-view /></main>
    </div>
  </div>
</template>
