// citrine/seeds/brand-yellow-e/bridge/vue/ConfirmBar.vue
<script setup>
// 浮层内的原位确认条（种子配方）：抽屉 / 弹窗里要确认「丢弃修改 / 确定关闭」时，不再叠第二层 MessageBox，
// 而是把浮层底部替换成一条确认区域——一句话 + 「留下」（次要，自动聚焦）+ 确认（主按钮；不可逆动作用 danger）。
// Esc 在条内 = 留下。配合 useInlineConfirm()：ask() 返回 Promise<boolean>，用法与 confirmLeave 一样。
import { onMounted, ref } from 'vue'
const props = defineProps({
  message: { type: String, required: true },
  confirmText: { type: String, default: '确定离开' },
  cancelText: { type: String, default: '留下' },
  danger: { type: Boolean, default: false }
})
const emit = defineEmits(['confirm', 'cancel'])
const cancelRef = ref()
onMounted(() => { cancelRef.value?.$el?.focus?.() })
</script>

<template>
  <div class="confirm-bar" role="alertdialog" aria-live="assertive" :aria-label="message" @keydown.esc.stop.prevent="emit('cancel')">
    <span class="msg">{{ message }}</span>
    <el-button ref="cancelRef" @click="emit('cancel')">{{ cancelText }}</el-button>
    <el-button :type="danger ? 'danger' : 'primary'" @click="emit('confirm')">{{ confirmText }}</el-button>
  </div>
</template>

// morganite/seeds/morganite/bridge/react/ConfirmBar.tsx
// 浮层内原位确认条（种子配方组件 · React 版，与 bridge/vue/ConfirmBar.vue 同形）：替换 Dialog / Sheet 页脚，不叠第二层弹窗。
// useInlineConfirm() 返回 { state, ask, confirm, cancel }，ask() 返回 Promise<boolean>。按钮用项目自己的 Button 组件传入（保持 shadcn 形态）。
import * as React from 'react'

export interface ConfirmBarProps {
  message: string
  confirmText?: string
  cancelText?: string
  danger?: boolean
  onConfirm: () => void
  onCancel: () => void
  renderButton?: (props: { variant: 'primary' | 'danger' | 'secondary'; onClick: () => void; children: React.ReactNode; autoFocus?: boolean }) => React.ReactNode
}

export function ConfirmBar({ message, confirmText = '确定离开', cancelText = '留下', danger = false, onConfirm, onCancel, renderButton }: ConfirmBarProps) {
  const cancelRef = React.useRef<HTMLButtonElement>(null)
  React.useEffect(() => { cancelRef.current?.focus() }, [])
  const btn = renderButton ?? (({ variant, onClick, children, autoFocus }) => (
    <button ref={autoFocus ? cancelRef : undefined} type="button" className={`confirm-bar__btn is-${variant}`} onClick={onClick}>{children}</button>
  ))
  return (
    <div className="confirm-bar" role="alertdialog" aria-live="assertive" aria-label={message} onKeyDown={(e) => { if (e.key === 'Escape') { e.stopPropagation(); e.preventDefault(); onCancel() } }}>
      <span className="msg">{message}</span>
      {btn({ variant: 'secondary', onClick: onCancel, children: cancelText, autoFocus: true })}
      {btn({ variant: danger ? 'danger' : 'primary', onClick: onConfirm, children: confirmText })}
    </div>
  )
}

export function useInlineConfirm() {
  const [state, setState] = React.useState({ open: false, message: '', confirmText: '确定离开', cancelText: '留下', danger: false })
  const pending = React.useRef<{ resolve: (ok: boolean) => void; promise: Promise<boolean> } | null>(null)
  const ask = React.useCallback((opts: { message: string; confirmText?: string; cancelText?: string; danger?: boolean }) => {
    if (pending.current) return pending.current.promise
    let resolve!: (ok: boolean) => void
    const promise = new Promise<boolean>((r) => { resolve = r })
    pending.current = { promise, resolve }
    setState({ open: true, message: opts.message, confirmText: opts.confirmText ?? '确定离开', cancelText: opts.cancelText ?? '留下', danger: opts.danger ?? false })
    return promise
  }, [])
  const settle = React.useCallback((ok: boolean) => { setState((s) => ({ ...s, open: false })); const p = pending.current; pending.current = null; p?.resolve(ok) }, [])
  return { state, ask, confirm: () => settle(true), cancel: () => settle(false) }
}
